services:
  movie-night-wheel:
    image: ghcr.io/its-goose/movie-night-wheel:latest
    container_name: movie-night-wheel
    ports:
      - "8090:3000"
    volumes:
      - /mnt/user/appdata/movie-night-wheel:/data
    restart: unless-stopped
